management/urls.py
from django.urls import path
from .views import *

app_name = 'management'

urlpatterns = [
    path('categories/', category_list, name='category_list'),
    path('category/create/', category_create, name='category_create'),
    path('category/<int:pk>/edit/', category_edit, name='category_edit'),
    path(
        'category/<int:pk>/delete/',
        category_delete,
        name='category_delete'
    ),

    path('products/', product_list, name='product_list'),
    path('product/create/', product_create, name='product_create'),
    path('product/<int:pk>/edit/', product_edit, name='product_edit'),
    path('product/<int:pk>/delete/', product_delete, name='product_delete'),

    path('orders/', order_list, name='order_list'),
    path('order/<int:pk>/', order_detail, name='order_detail'),
    path('order/<int:pk>/dispatch', order_dispatch, name='order_dispatch'),
    path('order/<int:pk>/deliver', order_deliver, name='order_deliver'),

    path('reviews/', review_list, name='review_list'),
    path(
        'review-active-toggle/<int:pk>/',
        review_active_toggle,
        name='review_active_toggle'
    ),

    path('users/', user_list, name='user_list'),
    path('user/<int:pk>/', user_detail, name='user_detail'),
]

myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', users_views.profile, name='account_profile'),
    path('', include('shop.urls', namespace='shop')),
    path('management/', include('management.urls', namespace='management')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', home, name='home'),
    path('shop/', product_list, name='product_list'),
    path('order-history/', order_list, name='order_list'),
    path('invoice/<int:pk>/', invoice, name='invoice'),
    path('cart/', cart, name='cart'),
    path('add-to-cart/<int:pk>/', add_to_cart, name='add_to_cart'),
    path('update-cart/<int:pk>/', update_cart, name='update_cart'),
    path('remove-from-cart/<int:pk>/', remove_from_cart, name='remove_from_cart'),
    path('checkout/', checkout, name='checkout'),
    path('success/', success, name='success'),
    path('cancel/', cancel, name='cancel'),
    path('webhooks/stripe/', stripe_webhook, name='stripe_webhook'),
    path('create-review/<int:pk>/', review_create, name='review_create'),
    path('<slug:slug>/', product_detail, name='product_detail'),
]

management/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.conf import settings
from django.contrib import admin
from django.core.exceptions import ValidationError
from django.core.validators import (
    MinLengthValidator,
    RegexValidator,
    MinValueValidator,
    MaxValueValidator
)
from django.db import models
from django.db.models import Avg, Sum
from django.utils import timezone
from django.utils.text import slugify

LABEL_COLOUR_CHOICES = (
    ('P','primary'),
    ('S','secondary'),
    ('Su','success'),
    ('D','danger'),
    ('W','warning'),
    ('I','info'),
)

DIALCODE_CHOICES = (
    ('+91', '+91 (India)'),
)

CITY_CHOICES = (
    ('Ah', 'Ahmednagar'),
    ('Ak', 'Akola'),
    ('Am', 'Amravati'),
    ('Au', 'Aurangabad'),
    ('Be', 'Beed'),
    ('Bh', 'Bhandara'), 
    ('Bu', 'Buldhana'),
    ('Ch', 'Chandrapur'),
    ('Dh', 'Dhule'),
    ('Ga', 'Gadchiroli'),
    ('Go', 'Gondia'),
    ('Hi', 'Hingoli'),
    ('Ja', 'Jalgaon'),
    ('Jan', 'Jalna'),
    ('Ko', 'Kolhapur'),
    ('La', 'Latur'),
    ('Mu', 'Mumbai'),
    ('Ng', 'Nagpur'),
    ('Na', 'Nanded'),
    ('Nab', 'Nandurbar'),
    ('Ns', 'Nashik'), 
    ('Os', 'Osmanabad'),
    ('Pa', 'Parbhani'),
    ('Pu', 'Pune'), 
    ('Ra', 'Raigad'),
    ('Rt', 'Ratnagiri'),
    ('Sa', 'Sangli'),
    ('St', 'Satara'),
    ('Si', 'Sindhudurg'),
    ('So', 'Solapur'), 
    ('Th', 'Thane'),
    ('Wa', 'Washim'),
    ('Ya', 'Yavatmal')
)

PAYMENT_CHOICES = (
    ('S','Stripe'),
    ('C','Cash on Delivery '),
)

class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    deleted = models.BooleanField(default=False)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        Category,
        related_name='products',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    description = models.TextField(max_length=1000)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True
    )
    available = models.BooleanField(default=True)
    label_colour = models.CharField(
        max_length=9,
        choices=LABEL_COLOUR_CHOICES,
        default='P'
    )
    label_text = models.CharField(max_length=20, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_final_price(self):
        if self.discount_price:
            return self.discount_price
        return self.price

    def get_num_rating(self):
        return self.reviews.filter(active=True).count()

    def get_avg_rating(self):
        rating = self.reviews.filter(active=True).aggregate(
            Avg('rating')
        )['rating__avg']

        return rating if rating else 0

    def get_income(self):
        income = self.items.exclude(order__delivered=None).aggregate(
            Sum('cost')
        )['cost__sum']

        return income if income else 0

    def get_sales(self):
        sales = self.items.exclude(order__delivered=None).aggregate(
            Sum('quantity')
        )['quantity__sum']

        return sales if sales else 0

    def get_demand(self):
        demand = self.items.exclude(order__placed=None).filter(
            order__dispatched=None,
            order__rejected=None
        ).aggregate(Sum('quantity'))['quantity__sum']

        return demand if demand else 0

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product,
        related_name='images',
        on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to='product_images/')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)


class Order(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='orders',
        on_delete=models.SET_NULL,
        null=True
    )
    placed = models.DateTimeField(null=True, blank=True)
    paid = models.DateTimeField(null=True, blank=True)
    dispatched = models.DateTimeField(null=True, blank=True)
    delivered = models.DateTimeField(null=True, blank=True)
    rejected = models.DateTimeField(null=True, blank=True)
    reject_reason = models.TextField(max_length=1000, blank=True)

    class Meta:
        ordering = ('-placed',)

    @admin.display(description='total cost')
    def get_total_cost(self):
        return sum(i.get_cost() for i in self.items.all())

    def get_total_discount(self):
        return sum(i.get_discount() for i in self.items.all())

    def can_checkout(self):
        return self.items.filter(product__available=True).exists()

    def place_order(self):
        self.placed = timezone.now()
        self.save()

        for item in self.items.filter(product__available=True):
            item.cost = item.get_cost()
            item.save()

        self.items.filter(
            product__available=False
        ).update(order=Order.objects.create(user=self.user))

    def clean(self):
        if not self.placed:
            if self.paid:
                raise ValidationError(
                    "Order can't be paid if its not placed"
                )
            if self.dispatched:
                raise ValidationError(
                    "Order can't be dispatched if its not placed"
                )
            if self.rejected:
                raise ValidationError(
                    "Order can't be rejected if its not placed"
                )
        if not self.dispatched and self.delivered:
            raise ValidationError(
                "Order can't be delivered if its not dispatched"
            )
        if self.paid and self.rejected:
            raise ValidationError(
                "Order can't be rejected if its paid"
            )

    def __str__(self):
        return f'Order #{self.pk}'


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        related_name='items',
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        Product,
        related_name='items',
        on_delete=models.CASCADE
    )
    quantity = models.PositiveIntegerField(
        default=1,
        validators=[MinValueValidator(1)]
    )
    cost = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True
    )

    def get_cost(self):
        if self.cost:
            return self.cost
        elif self.product.available:
            return self.quantity * self.product.get_final_price()
        else:
            return 0

    def get_discount(self):
        if not (self.product.discount_price and self.product.available):
            return 0

        discount = self.product.price - self.product.discount_price
        return self.quantity * discount

    def __str__(self):
        return f'{self.product} x{self.quantity}'


class OrderDetails(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    dial_code = models.CharField(
        max_length=4,
        choices=DIALCODE_CHOICES,
        default='+91',
    )
    phone = models.CharField(
        max_length=15,
        validators=[
            MinLengthValidator(4),
            RegexValidator(
                regex=r'^\d*$',
                message='Only digits are allowed.'
            )
        ]
    )
    address = models.CharField(max_length=250)
    city = models.CharField(
        choices=CITY_CHOICES,
        max_length=3,
        default='Mu'
    )
    postal_code = models.CharField(max_length=20)
    payment_method = models.CharField(
        choices=PAYMENT_CHOICES,
        max_length=1,
        default='S'
    )

    class Meta:
        verbose_name = 'order details'
        verbose_name_plural = 'order details'

    def __str__(self):
        return f'{self.order} Details'


class Review(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='reviews',
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        Product,
        related_name='reviews',
        on_delete=models.CASCADE
    )
    rating = models.PositiveIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    comment = models.TextField(max_length=1000, blank=True)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

management/forms.py
from django import forms
from django.forms import modelformset_factory, inlineformset_factory
from shop.models import Category, Product, ProductImage, Order

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class ProductImageForm(forms.ModelForm):
    class Meta:
        model = ProductImage
        fields = ('image',)


class OrderRejectForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('reject_reason',)
        widgets = {
            'reject_reason': forms.Textarea(attrs={'rows': 7})
        }


ProductImageModelFormSet = modelformset_factory(
    ProductImage,
    form=ProductImageForm,
    extra=3
)

ProductImageInlineFormSet = inlineformset_factory(
    Product,
    ProductImage,
    form=ProductImageForm,
    extra=1
)

management/templates/management/category_list.html
{% extends "management/base.html" %}

{% block title %}Categories{% endblock title %}

{% block content %}
  <!-- Heading -->
  <div class="card mb-4 wow fadeIn">

    <!--Card content-->
    <div class="card-body d-sm-flex justify-content-between">

      <h4 class="mb-2 mb-sm-0 pt-1">Categories</h4>

    </div>

  </div>
  <!-- Heading -->

  <!--Card-->
  <div class="card">

    <!--Card content-->
    <div class="card-body">

      <a href="{% url 'management:category_create' %}" class="btn btn-md btn-primary ">Create category</a>

      <div class="table-responsive mt-4">
        <table class="table table-sm table-bordered">
          <thead class="thead-light">
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Name</th>
              <th scope="col">Products</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            {% for category in categories %}
              <tr>
                <td>{{ category.id }}</td>
                <td>{{ category }}</td>
                <td>{{ category.products.count }}</td>
                <td>
                  <a href="{% url 'management:category_edit' category.pk %}" class="btn btn-sm btn-default">Edit</a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

    </div>

  </div>
{% endblock content %}

management/templates/management/navbar.html
 <!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container-fluid">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="https://mdbootstrap.com/docs/jquery/" target="_blank">
      <strong class="blue-text">Ecommerce Admin</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    {% with url_name=request.resolver_match.url_name %}
    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if url_name in 'order_list order_detail' %}active{% endif %}">
          <a class="nav-link waves-effect" href="{% url 'management:order_list' %}">Orders</a>
        </li>
        <li class="nav-item {% if url_name in 'category_list category_create category_edit' %}active{% endif %}">
          <a class="nav-link waves-effect" href="{% url 'management:category_list' %}">Categories</a>
        </li>
        <li class="nav-item {% if url_name in 'product_list product_create product_edit' %}active{% endif %}">
          <a class="nav-link waves-effect" href="{% url 'management:product_list' %}">Products</a>
        </li>
        <li class="nav-item {% if url_name in 'review_list' %}active{% endif %}">
          <a class="nav-link waves-effect" href="{% url 'management:review_list' %}">Reviews</a>
        </li>
        <li class="nav-item {% if url_name in 'user_list user_detail' %}active{% endif %}">
          <a class="nav-link waves-effect" href="{% url 'management:user_list' %}">Users</a>
        </li>
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        <div class="btn-group">
          <button class="btn btn-sm btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i></button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'shop:home' %}">View site</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'account_profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
          </div>
        </div>
      </ul>

    </div>
    {% endwith %}

  </div>
</nav>
<!-- Navbar -->

management/templates/management/order_detail.html
{% extends "management/base.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% load my_extras %}

{% block title %}{{ order }}{% endblock title %}

{% block content %}
  <!-- Heading -->
  <div class="card mb-4 wow fadeIn">

    <!--Card content-->
    <div class="card-body d-sm-flex justify-content-between">

      <h4 class="mb-2 mb-sm-0 pt-1">
        <a href="{% url 'management:order_list' %}">Orders</a>
        <span>/ {{ order.id }}</span>
      </h4>

    </div>

  </div>
  <!-- Heading -->

  <div class="card-deck">
    <!--Card-->
    <div class="card mb-3">

      <!--Card content-->
      <div class="card-body">

        <h2 class="card-title font-weight-bold">Order</h2>
        <hr>
        <table>
          <tr>
            <td class="w-50" valign="top">Order ID:</td>
            <td>{{ order.id }}</td>
          </tr>
          <tr>
            <td valign="top">User:</td>
            <td>{{ order.user }}</td>
          </tr>
          <tr>
            <td valign="top">Placed on:</td>
            <td>{{ order.placed }}</td>
          </tr>
          <tr>
            <td valign="top">Price:</td>
            <td>${{ order.get_total_cost }}</td>
          </tr>
          <tr>
            <td valign="top">Payment:</td>
            <td>
              {% if order.paid %}
                <span class="badge bg-success">Paid</span>
              {% else %}
                <span class="badge bg-warning">Pending</span>
              {% endif %}
            </td>
          </tr>
          {% if order.paid %}
            <tr>
              <td valign="top">Paid on:</td>
              <td>{{ order.paid }}</td>
            </tr>
          {% endif %}
          {% if order.dispatched %}
            <tr>
              <td valign="top">Dispatched on:</td>
              <td>{{ order.dispatched }}</td>
            </tr>
          {% endif %}
          {% if order.delivered %}
            <tr>
              <td valign="top">Delivered on:</td>
              <td>{{ order.delivered }}</td>
            </tr>
          {% endif %}
          {% if order.rejected %}
            <tr>
              <td valign="top">Rejected on:</td>
              <td>{{ order.rejected }}</td>
            </tr>
            {% if order.reject_reason %}
              <tr>
                <td valign="top">Reject reason:</td>
                <td>{{ order.reject_reason }}</td>
              </tr>
            {% endif %}
          {% endif %}
          <tr>
            <td valign="top">Status:</td>
            <td>
              <span class="badge bg-{{ order|order_status|order_status_colour }}">
                {{ order|order_status }}
              </span>
            </td>
          </tr>
          <tr>
            <td valign="top">Invoice:</td>
            <td><a href="{% url 'shop:invoice' order.pk %}" class="text-primary">PDF</a></td>
          </tr>
        </table>

        {% if not order.rejected and not order.delivered %}
          <form action="{% if not order.dispatched %}{% url 'management:order_dispatch' order.pk %}{% else %}{% url 'management:order_deliver' order.pk %}{% endif %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-success mt-4">
              {% if not order.dispatched %}
                Dispatch
              {% elif order.paid %}
                Deliver
              {% else %}
                Pay and Deliver
              {% endif %}
            </button>
          </form>
        {% endif %}

      </div>

    </div>

    <!--Card-->
    <div class="card mb-3">

      <!--Card content-->
      <div class="card-body">

        <h2 class="card-title font-weight-bold">Address</h2>
        <hr>
        <table>
          <tr>
            <td class="w-50" valign="top">First name:</td>
            <td>{{ order.orderdetails.first_name }}</td>
          </tr>
          <tr>
            <td valign="top">Last name:</td>
            <td>{{ order.orderdetails.last_name }}</td>
          </tr>
          <tr>
            <td valign="top">Email:</td>
            <td>{{ order.orderdetails.email }}</td>
          </tr>
          <tr>
            <td valign="top">Dial code:</td>
            <td>{{ order.orderdetails.dial_code }}</td>
          </tr>
          <tr>
            <td valign="top">Phone:</td>
            <td>{{ order.orderdetails.phone }}</td>
          </tr>
          <tr>
            <td valign="top">Address:</td>
            <td>{{ order.orderdetails.address }}</td>
          </tr>
          <tr>
            <td valign="top">City:</td>
            <td>{{ order.orderdetails.get_city_display }}</td>
          </tr>
          <tr>
            <td valign="top">Postal code:</td>
            <td>{{ order.orderdetails.postal_code }}</td>
          </tr>
          <tr>
            <td valign="top">Payment method:</td>
            <td>{{ order.orderdetails.get_payment_method_display }}</td>
          </tr>
        </table>

      </div>

    </div>
  </div>

  <div class="card mb-3">
    <div class="card-body">
      <h2 class="card-title font-weight-bold">Order Items</h2>
      <hr>
      <div class="table-responsive mt-4">
        <table class="table table-sm table-bordered">
          <thead class="thead-light">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Image</th>
              <th scope="col">Product</th>
              <th scope="col">Quantity</th>
              <th scope="col">Unit price</th>
              <th scope="col">Price</th>
              <th scope="col">Available</th>
            </tr>
          </thead>
          <tbody>
            {% for item in order.items.all %}
              <tr>
                <th scope="row" class="align-middle">{{ forloop.counter }}</th>
                <td>
                  <img src="{% if item.product.images.first %}{{ item.product.images.first.image.url }}{% else %}{% static 'shop/img/no_image.png' %}{% endif %}" style="height:70px; width:70px;">
                </td>
                <td>{{ item.product }}</td>
                <td>{{ item.quantity }}</td>
                <td>${{ item.product.price }}</td>
                <td>${{ item.get_cost }}</td>
                <td>{% if not item.product.deleted %}{{ item.product.available }}{% endif %}</td>
              </tr>
            {% endfor %}
            <thead class="thead-light">
              <tr>
                <th colspan="6" class="font-weight-bold">Total</th>
                <th class="font-weight-bold">${{ order.get_total_cost }}</th>
              </tr>
            </thead>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  {% if not order.rejected and not order.paid %}
    <div class="card mx-auto mw-1">
      <div class="card-body">
        <h2 class="card-title font-weight-bold">Reject Order</h2>
        <hr>
        <form method="POST">
          {% csrf_token %}
          {{ form|crispy }}
          <button class="btn btn-danger">Reject</button>
        </form>
      </div>
    </div>  
  {% endif %}
  
{% endblock content %}

management/templates/management/sidebar.html
<!-- Sidebar -->
<div class="sidebar-fixed position-fixed">

  {% with url_name=request.resolver_match.url_name %}
  <div class="list-group list-group-flush mt-5">
    <a href="{% url 'management:order_list' %}" class="list-group-item {% if url_name in 'order_list order_detail' %}active{% else %}list-group-item-action{% endif %} waves-effect">
      <i class="fas fa-truck mr-3"></i>Orders</a>
    <a href="{% url 'management:category_list' %}" class="list-group-item {% if url_name in 'category_list category_create category_edit' %}active{% else %}list-group-item-action{% endif %} waves-effect">
      <i class="fas fa-tags mr-3"></i>Categories</a>
    <a href="{% url 'management:product_list' %}" class="list-group-item {% if url_name in 'product_list product_create product_edit' %}active{% else %}list-group-item-action{% endif %} waves-effect">
      <i class="fas fa-boxes mr-3"></i>Products</a>
    <a href="{% url 'management:review_list' %}" class="list-group-item {% if url_name in 'review_list' %}active{% else %}list-group-item-action{% endif %} waves-effect">
      <i class="fas fa-comment mr-3"></i>Reviews</a>
    <a href="{% url 'management:user_list' %}" class="list-group-item {% if url_name in 'user_list user_detail' %}active{% else %}list-group-item-action{% endif %} waves-effect">
      <i class="fas fa-users mr-3"></i>Users</a>
  </div>
  {% endwith %}

</div>
<!-- Sidebar -->

management/templates/management/user_detail.html
{% extends "management/base.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% load my_extras %}

{% block title %}{{ user }}{% endblock title %}

{% block content %}
  <!-- Heading -->
  <div class="card mb-4 wow fadeIn">

    <!--Card content-->
    <div class="card-body d-sm-flex justify-content-between">

      <h4 class="mb-2 mb-sm-0 pt-1">
        <a href="{% url 'management:user_list' %}">Users</a>
        <span>/ {{ user.id }}</span>
      </h4>

    </div>

  </div>
  <!-- Heading -->

  <div class="card-deck">
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title">Income from this user</h5>
        <p>${{ user.get_income }}</p>
      </div>
    </div>

    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title">Orders pending</h5>
        <p>{{ user.get_orders_pending }}</p>
      </div>
    </div>

    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title">Deliveries pending</h5>
        <p>{{ user.get_deliveries_pending }}</p>
      </div>
    </div>
  </div>

  <!--Card-->
  <div class="card mb-3 mw-1">

    <!--Card content-->
    <div class="card-body">

      <h2 class="card-title font-weight-bold">User</h2>
      <hr>
      <table>
        <tr>
          <td class="w-50" valign="top">User ID:</td>
          <td>{{ user.id }}</td>
        </tr>
        <tr>
          <td valign="top">Username:</td>
          <td>{{ user.username }}</td>
        </tr>
        <tr>
          <td valign="top">Email:</td>
          <td>{{ user.email }}</td>
        </tr>
        <tr>
          <td valign="top">First name:</td>
          <td>{{ user.first_name }}</td>
        </tr>
        <tr>
          <td valign="top">Last name:</td>
          <td>{{ user.last_name }}</td>
        </tr>
        <tr>
          <td valign="top">Last login on:</td>
          <td>{{ user.last_login }}</td>
        </tr>
        <tr>
          <td valign="top">Joined on:</td>
          <td>{{ user.date_joined }}</td>
        </tr>
      </table>

    </div>

  </div>

  <div class="card mb-3">
    <div class="card-body">
      <h2 class="card-title font-weight-bold">Orders</h2>
      <hr>
      <div class="table-responsive mt-4">
        <table class="table table-sm table-bordered">
          <thead class="thead-light">
            <tr>
              <th scope="col">ID</th>
              <th scope="col">User</th>
              <th scope="col">Placed on</th>
              <th scope="col">Price</th>
              <th scope="col">Payment</th>
              <th scope="col">Status</th>
              <th scope="col">Invoice</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            {% for order in orders %}
              <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.user }}</td>
                <td>{{ order.placed }}</td>
                <td>${{ order.get_total_cost }}</td>
                <td>
                  {% if order.paid %}
                    <span class="badge bg-success">Paid</span>
                  {% else %}
                    <span class="badge bg-warning">Pending</span>
                  {% endif %}
                </td>
                <td>
                  <span class="badge bg-{{ order|order_status|order_status_colour }}">
                    {{ order|order_status }}
                  </span>
                </td>
                <td><a href="{% url 'shop:invoice' order.pk %}" class="text-primary">PDF</a></td>
                <td>
                  <a href="{% url 'management:order_detail' order.pk %}" class="btn btn-sm btn-default">View</a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}