myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', users_views.profile, name='account_profile'),
    path('', include('shop.urls', namespace='shop')),
    path('management/', include('management.urls', namespace='management')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', home, name='home'),
    path('shop/', product_list, name='product_list'),
    path('order-history/', order_list, name='order_list'),
    path('invoice/<int:pk>/', invoice, name='invoice'),
    path('cart/', cart, name='cart'),
    path('add-to-cart/<int:pk>/', add_to_cart, name='add_to_cart'),
    path('update-cart/<int:pk>/', update_cart, name='update_cart'),
    path('remove-from-cart/<int:pk>/', remove_from_cart, name='remove_from_cart'),
    path('checkout/', checkout, name='checkout'),
    path('success/', success, name='success'),
    path('cancel/', cancel, name='cancel'),
    path('webhooks/stripe/', stripe_webhook, name='stripe_webhook'),
    path('create-review/<int:pk>/', review_create, name='review_create'),
    path('<slug:slug>/', product_detail, name='product_detail'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>Ecommerce | {% block title %}{% endblock title %}</title>
  {% block extra_head %}{% endblock extra_head %}

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    .mw-1 {
      max-width: 730px;
    }
    .cursor-pointer {
      cursor: pointer;
    }
    .quantity-input {
      width: 100px;
    }

  </style>
</head>

<body>

  {% include 'navbar.html' %}

  {% if messages%}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} rounded-0 mb-0">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  {% endif%} 

  {% block content %}{% endblock content %}
  {% block extra_body %}{% endblock extra_body %}

  {% include 'footer.html' %}

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>

  {% block extra_scripts %}{% endblock extra_scripts %}

</body>

</html>

templates/footer.html
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

  <!--Copyright-->
  <div class="footer-copyright py-3">
    © 2019 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
  </div>
  <!--/.Copyright-->

</footer>
<!--/.Footer-->

templates/navbar.html
{% load my_extras %}

<!-- Navbar -->
<nav class="navbar sticky-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="#" target="_blank">
      <strong class="blue-text">Ecommerce</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    {% with url_name=request.resolver_match.url_name %}
    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if url_name == 'home' %}active{% endif %}">
          <a class="nav-link waves-effect" href="{% url 'shop:home' %}">Home</a>
        </li>
        <li class="nav-item {% if url_name == 'product_list' %}active{% endif %}">
          <a class="nav-link waves-effect" href="{% url 'shop:product_list' %}">Shop</a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="#" target="_blank">Contact</a>
        </li>
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'shop:cart' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <div class="btn-group">
            <button class="btn btn-sm btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i></button>
            <div class="dropdown-menu">
              {% if user|has_group:'admin' %}
                <a class="dropdown-item" href="{% url 'management:order_list' %}">Admin</a>
                <div class="dropdown-divider"></div>
              {% endif %}
              <a class="dropdown-item" href="{% url 'account_profile' %}">Profile</a>
              <a class="dropdown-item" href="{% url 'shop:order_list' %}">Orders</a>
              <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
            </div>
          </div>
        {% else %}
          <li class="nav-item">
            <a href="{% url 'account_login' %}" class="btn btn-primary btn-sm waves-effect">Sign In</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'account_signup' %}" class="btn btn-secondary btn-sm waves-effect">Sign Up</a>
          </li>
        {% endif %}
      </ul>

    </div>
    {% endwith %}
  </div>
</nav>
<!-- Navbar -->

templates/pagination.html
<!--Pagination-->
<nav class="d-flex justify-content-center wow fadeIn">
  <ul class="pagination pg-blue">

    <!--Arrow left-->
    {% if page.has_previous %}
      <li class="page-item">
        <a class="page-link js-keep-params" href="?page={{ page.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
    {% endif %}

    {% for num in page.paginator.page_range %}
      {% if page.number == num %}
        <li class="page-item active">
          <a class="page-link js-keep-params" href="?page={{ num }}">{{ num }}
            <span class="sr-only">(current)</span>
          </a>
        </li>
      {% elif num > page.number|add:'-3' and num < page.number|add:'3' %}
        <li class="page-item">
          <a class="page-link js-keep-params" href="?page={{ num }}">{{ num }}</a>
        </li>
      {% endif %}
    {% endfor %}

    {% if page.has_next %}
      <li class="page-item">
        <a class="page-link js-keep-params" href="?page={{ page.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
<!--Pagination-->