myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', users_views.profile, name='account_profile'),
    path('', include('shop.urls', namespace='shop')),
    path('management/', include('management.urls', namespace='management')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', home, name='home'),
    path('shop/', product_list, name='product_list'),
    path('order-history/', order_list, name='order_list'),
    path('invoice/<int:pk>/', invoice, name='invoice'),
    path('cart/', cart, name='cart'),
    path('add-to-cart/<int:pk>/', add_to_cart, name='add_to_cart'),
    path('update-cart/<int:pk>/', update_cart, name='update_cart'),
    path('remove-from-cart/<int:pk>/', remove_from_cart, name='remove_from_cart'),
    path('checkout/', checkout, name='checkout'),
    path('success/', success, name='success'),
    path('cancel/', cancel, name='cancel'),
    path('webhooks/stripe/', stripe_webhook, name='stripe_webhook'),
    path('create-review/<int:pk>/', review_create, name='review_create'),
    path('<slug:slug>/', product_detail, name='product_detail'),
]

shop/models.py
from django.conf import settings
from django.contrib import admin
from django.core.exceptions import ValidationError
from django.core.validators import (
    MinLengthValidator,
    RegexValidator,
    MinValueValidator,
    MaxValueValidator
)
from django.db import models
from django.db.models import Avg, Sum
from django.utils import timezone
from django.utils.text import slugify

LABEL_COLOUR_CHOICES = (
    ('P','primary'),
    ('S','secondary'),
    ('Su','success'),
    ('D','danger'),
    ('W','warning'),
    ('I','info'),
)

DIALCODE_CHOICES = (
    ('+91', '+91 (India)'),
)

CITY_CHOICES = (
    ('Ah', 'Ahmednagar'),
    ('Ak', 'Akola'),
    ('Am', 'Amravati'),
    ('Au', 'Aurangabad'),
    ('Be', 'Beed'),
    ('Bh', 'Bhandara'), 
    ('Bu', 'Buldhana'),
    ('Ch', 'Chandrapur'),
    ('Dh', 'Dhule'),
    ('Ga', 'Gadchiroli'),
    ('Go', 'Gondia'),
    ('Hi', 'Hingoli'),
    ('Ja', 'Jalgaon'),
    ('Jan', 'Jalna'),
    ('Ko', 'Kolhapur'),
    ('La', 'Latur'),
    ('Mu', 'Mumbai'),
    ('Ng', 'Nagpur'),
    ('Na', 'Nanded'),
    ('Nab', 'Nandurbar'),
    ('Ns', 'Nashik'), 
    ('Os', 'Osmanabad'),
    ('Pa', 'Parbhani'),
    ('Pu', 'Pune'), 
    ('Ra', 'Raigad'),
    ('Rt', 'Ratnagiri'),
    ('Sa', 'Sangli'),
    ('St', 'Satara'),
    ('Si', 'Sindhudurg'),
    ('So', 'Solapur'), 
    ('Th', 'Thane'),
    ('Wa', 'Washim'),
    ('Ya', 'Yavatmal')
)

PAYMENT_CHOICES = (
    ('S','Stripe'),
    ('C','Cash on Delivery '),
)

class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    deleted = models.BooleanField(default=False)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        Category,
        related_name='products',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    description = models.TextField(max_length=1000)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True
    )
    available = models.BooleanField(default=True)
    label_colour = models.CharField(
        max_length=9,
        choices=LABEL_COLOUR_CHOICES,
        default='P'
    )
    label_text = models.CharField(max_length=20, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_final_price(self):
        if self.discount_price:
            return self.discount_price
        return self.price

    def get_num_rating(self):
        return self.reviews.filter(active=True).count()

    def get_avg_rating(self):
        rating = self.reviews.filter(active=True).aggregate(
            Avg('rating')
        )['rating__avg']

        return rating if rating else 0

    def get_income(self):
        income = self.items.exclude(order__delivered=None).aggregate(
            Sum('cost')
        )['cost__sum']

        return income if income else 0

    def get_sales(self):
        sales = self.items.exclude(order__delivered=None).aggregate(
            Sum('quantity')
        )['quantity__sum']

        return sales if sales else 0

    def get_demand(self):
        demand = self.items.exclude(order__placed=None).filter(
            order__dispatched=None,
            order__rejected=None
        ).aggregate(Sum('quantity'))['quantity__sum']

        return demand if demand else 0

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product,
        related_name='images',
        on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to='product_images/')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)


class Order(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='orders',
        on_delete=models.SET_NULL,
        null=True
    )
    placed = models.DateTimeField(null=True, blank=True)
    paid = models.DateTimeField(null=True, blank=True)
    dispatched = models.DateTimeField(null=True, blank=True)
    delivered = models.DateTimeField(null=True, blank=True)
    rejected = models.DateTimeField(null=True, blank=True)
    reject_reason = models.TextField(max_length=1000, blank=True)

    class Meta:
        ordering = ('-placed',)

    @admin.display(description='total cost')
    def get_total_cost(self):
        return sum(i.get_cost() for i in self.items.all())

    def get_total_discount(self):
        return sum(i.get_discount() for i in self.items.all())

    def can_checkout(self):
        return self.items.filter(product__available=True).exists()

    def place_order(self):
        self.placed = timezone.now()
        self.save()

        for item in self.items.filter(product__available=True):
            item.cost = item.get_cost()
            item.save()

        self.items.filter(
            product__available=False
        ).update(order=Order.objects.create(user=self.user))

    def clean(self):
        if not self.placed:
            if self.paid:
                raise ValidationError(
                    "Order can't be paid if its not placed"
                )
            if self.dispatched:
                raise ValidationError(
                    "Order can't be dispatched if its not placed"
                )
            if self.rejected:
                raise ValidationError(
                    "Order can't be rejected if its not placed"
                )
        if not self.dispatched and self.delivered:
            raise ValidationError(
                "Order can't be delivered if its not dispatched"
            )
        if self.paid and self.rejected:
            raise ValidationError(
                "Order can't be rejected if its paid"
            )

    def __str__(self):
        return f'Order #{self.pk}'


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        related_name='items',
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        Product,
        related_name='items',
        on_delete=models.CASCADE
    )
    quantity = models.PositiveIntegerField(
        default=1,
        validators=[MinValueValidator(1)]
    )
    cost = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True
    )

    def get_cost(self):
        if self.cost:
            return self.cost
        elif self.product.available:
            return self.quantity * self.product.get_final_price()
        else:
            return 0

    def get_discount(self):
        if not (self.product.discount_price and self.product.available):
            return 0

        discount = self.product.price - self.product.discount_price
        return self.quantity * discount

    def __str__(self):
        return f'{self.product} x{self.quantity}'


class OrderDetails(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    dial_code = models.CharField(
        max_length=4,
        choices=DIALCODE_CHOICES,
        default='+91',
    )
    phone = models.CharField(
        max_length=15,
        validators=[
            MinLengthValidator(4),
            RegexValidator(
                regex=r'^\d*$',
                message='Only digits are allowed.'
            )
        ]
    )
    address = models.CharField(max_length=250)
    city = models.CharField(
        choices=CITY_CHOICES,
        max_length=3,
        default='Mu'
    )
    postal_code = models.CharField(max_length=20)
    payment_method = models.CharField(
        choices=PAYMENT_CHOICES,
        max_length=1,
        default='S'
    )

    class Meta:
        verbose_name = 'order details'
        verbose_name_plural = 'order details'

    def __str__(self):
        return f'{self.order} Details'


class Review(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='reviews',
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        Product,
        related_name='reviews',
        on_delete=models.CASCADE
    )
    rating = models.PositiveIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    comment = models.TextField(max_length=1000, blank=True)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

shop/forms.py
from django import forms
from .models import (
    Category,
    OrderItem,
    OrderDetails,
    Review,
    PAYMENT_CHOICES
)

PRODUCT_FILTER_INITIAL = {
    'sort_by': '-created',
    'search': None,
    'category': None,
    'min_price': None,
    'max_price': None,
    'min_rating': None,
    'include_out_of_stock': None,
}

SORT_BY_CHOICES = (
    ('-created', 'Newest First'),
    ('price', 'Price low to high'),
    ('-price', 'Price high to low'),
    ('-rating', 'Highest rating'),
)

class ProductFilterForm(forms.Form):
    sort_by = forms.ChoiceField(
        choices=SORT_BY_CHOICES,
        required=False
    )
    search = forms.CharField(
        max_length=100,
        required=False
    )
    category = forms.ModelChoiceField(
        queryset=Category.objects.exclude(deleted=True),
        empty_label='All',
        required=False,
    )
    min_price = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        required=False
    )
    max_price = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        required=False
    )
    min_rating = forms.IntegerField(
        max_value=5,
        min_value=1,
        required=False
    )
    include_out_of_stock = forms.BooleanField(required=False)


class AddToCartForm(forms.Form):
    quantity = forms.IntegerField(
        initial=1,
        max_value=20,
        min_value=1,
        widget=forms.NumberInput(
            attrs={'class': 'form-control quantity-input'}
        )
    )


class UpdateCartForm(forms.ModelForm):
    quantity = forms.IntegerField(
        min_value=1,
        widget=forms.NumberInput(
            attrs={'class': 'form-control d-inline quantity-input'}
        )
    )

    class Meta:
        model = OrderItem
        fields = ['quantity']


class CheckoutForm(forms.ModelForm):
    payment_method = forms.ChoiceField(
        choices=PAYMENT_CHOICES,
        widget=forms.RadioSelect()
    )

    class Meta:
        model = OrderDetails
        exclude = ['order']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'rating': forms.HiddenInput(),
            'comment': forms.Textarea(attrs={'rows': 5})
        }

shop/templates/shop/cancel.html
{% extends "base.html" %}

{% block title %}Cancel{% endblock title %}

{% block content %}
  <div class="container my-4">
    <h1>Order cancelled.</h1>
  </div>
{% endblock content %}

shop/templates/shop/cart.html
{% extends "base.html" %}

{% load static %}
{% load my_extras %}

{% block title %}Cart{% endblock title %}

{% block content %}
  <div class="container dark-grey-text mt-4">
    {% if order and order.items.all %}
      <h1>Shoping cart</h1>
      <div class="table-responsive mt-4">
        <table class="table table-sm">
          <thead class="thead-light">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Image</th>
              <th scope="col">Product</th>
              <th scope="col">Quantity</th>
              <th scope="col">Remove</th>
              <th scope="col">Unit price</th>
              <th scope="col">Price</th>
            </tr>
          </thead>
          <tbody>
            {% for item in order.items.all %}
              <tr>
                <th scope="row" class="align-middle">{{ forloop.counter }}</th>
                <td class="align-middle">
                  <img src="{% if item.product.images.first %}{{ item.product.images.first.image.url }}{% else %}{% static 'shop/img/no_image.png' %}{% endif %}" style="height:100px; width:100px;">
                </td>
                <td class="align-middle">
                  <a href="{% url 'shop:product_detail' item.product.slug %}" class="text-primary font-weight-bold">{{ item.product }}</a>
                </td>
                {% if item.product.available %}
                  <td class="align-middle">
                    <form action="{% url 'shop:update_cart' pk=item.pk %}" method="POST" class="d-flex">
                      {% csrf_token %}
                      {% with forms|get_item:item.pk as form %}
                        {{ form.quantity }}
                      {% endwith %}
                      <button class="btn btn-sm btn-primary"><i class="fas fa-sync-alt"></i></button>
                    </form>
                  </td>
                {% else %}
                  <td class="align-middle text-danger">Out of Stock</td>
                {% endif %}
                <td class="align-middle">
                  <form action="{% url 'shop:remove_from_cart' item.pk %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-sm btn-danger"><i class="fas fa-trash-alt"></i></button>
                  </form>
                </td>
                {% if item.product.available %}
                  <td class="align-middle">${{ item.product.price }}</td>
                  <td class="align-middle">
                    <div class="d-flex">
                      ${{ item.get_cost }}
                      {% if item.get_discount %}
                        <span class="badge success-color-dark ml-2 p-2">Saving ${{ item.get_discount }}</span>
                      {% endif %}
                    </div>
                  </td>
                {% endif %}
              </tr>
            {% endfor %}
            <thead class="thead-light">
              <tr>
                <th colspan="6" class="font-weight-bold">Total</th>
                <th class="font-weight-bold">${{ order.get_total_cost }}</th>
              </tr>
            </thead>
          </tbody>
        </table>
      </div>
      <div class="text-right">
        {% if order.get_total_discount %}
          <p class="green-text font-weight-bold">You will save ${{ order.get_total_discount }} on this order</p>
        {% endif %}
        <a href="{% url 'shop:product_list' %}" class="btn btn-default">Continue Shoping</a>
        {% if order.can_checkout %}
          <a href="{% url 'shop:checkout' %}" class="btn btn-primary">Place Order</a>
        {% endif %}
      </div>

      {% if recommended_products %}
        <h2 class="mb-4 mt-2">People who bought this also bought</h2>

        <!--Grid row-->
        <div class="row wow fadeIn">

          {% for product in recommended_products %}
            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-4">
              {% include 'shop/product_card.html' %}
            </div>
            <!--Grid column-->
          {% endfor %}

        </div>
        <!--Grid row-->
      {% endif %}

    {% else %}
      <h1>Your Cart is Empty</h1>
    {% endif %}
  </div>
{% endblock content %}

shop/templates/shop/checkout.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load my_extras %}

{% block title %}Checkout{% endblock title %}

{% block content %}
  <!--Main layout-->
  <main>
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form action="{% url 'shop:checkout' %}" method="POST" class="card-body">
              {% csrf_token %}
              {{ form|crispy }}
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">{{ items|length }}</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            {% for item in items %}
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">{{ item }}</h6>
                  {# <small class="text-muted">Brief description</small> #}
                </div>
                <span class="text-muted">${{ item.get_cost }}</span>
              </li>
            {% endfor %}
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>${{ order.get_total_cost }}</strong>
            </li>
          </ul>
          <!-- Cart -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
{% endblock content %}

shop/templates/shop/invoice.html
<html>
<body>
  <h1>Ecommerce</h1>
  <p>
    Order ID {{ order.id }}</br>
    <span class="secondary">
      {{ order.placed|date:"M d, Y" }}
    </span>
  </p>

  <h3>To</h3>
  <p>
    {{ order.orderdetails.first_name }} {{ order.orderdetails.last_name }}<br>
    {{ order.orderdetails.email }}<br>
    {{ order.orderdetails.address }}<br>
    {{ order.orderdetails.postal_code }}, {{ order.orderdetails.get_city_display }}
  </p>

  <h3>Items bought</h3>
  <table>
    <thead>
      <tr>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Cost</th>
      </tr>
    </thead>
    <tbody>
      {% for item in order.items.all %}
        <tr class="row{% cycle '1' '2' %}">
          <td>{{ item.product.name }}</td>
          <td class="num">${{ item.product.get_final_price }}</td>
          <td class="num">{{ item.quantity }}</td>
          <td class="num">${{ item.get_cost }}</td>
        </tr>
      {% endfor %}
      <tr class="total">
        <td colspan="3">Total</td>
        <td class="num">${{ order.get_total_cost }}</td>
      </tr>
    </tbody>
  </table>

  <span class="{% if order.paid %}paid{% else %}pending{% endif %}">
    {% if order.paid %}Paid{% else %}Pending payment{% endif %}
  </span>
</body>
</html>

shop/templates/shop/order_list.html
{% extends "base.html" %}

{% load static %}
{% load my_extras %}

{% block title %}Order History{% endblock title %}

{% block content %}
  <div class="container dark-grey-text mt-4">
    {% if orders %}
      <h1>Order history</h1>
      <div class="table-responsive mt-4">
        <table class="table table-bordered table-sm">
          <thead class="thead-light">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Order ID</th>
              <th scope="col">Placed on</th>
              <th scope="col">Price</th>
              <th scope="col">Payment</th>
              <th scope="col">Status</th>
              <th scope="col">Invoice</th>
            </tr>
          </thead>
          <tbody>
            {% for order in orders %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ order.id }}</td>
                <td>{{ order.placed|date:"M d, Y" }}</td>
                <td>${{ order.get_total_cost }}</td>
                <td>
                  {% if order.paid %}
                    <span class="badge bg-success">Paid</span>
                  {% else %}
                    <span class="badge bg-warning">Pending</span>
                  {% endif %}
                </td>
                <td>
                  <span class="badge bg-{{ order|order_status|order_status_colour }}">
                    {{ order|order_status }}
                  </span>
                </td>
                <td><a href="{% url 'shop:invoice' order.pk %}" class="text-primary">PDF</a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <h1>Your order history is empty</h1>
    {% endif %}
  </div>
{% endblock content %}

shop/templates/shop/product_card.html
{% load static %}
{% load my_extras %}

<!--Card-->
<div class="card">

  <!--Card image-->
  <div class="view overlay">
    <img src="{% if product.images.first %}{{ product.images.first.image.url }}{% else %}{% static 'shop/img/no_image.png' %}{% endif %}" class="card-img-top" alt="">
    <a href="{% url 'shop:product_detail' product.slug %}">
      <div class="mask rgba-white-slight"></div>
    </a>
  </div>
  <!--Card image-->

  <!--Card content-->
  <div class="card-body text-center">
    <!--Category & Title-->
    <a href="{% url 'shop:product_list' %}?category={{ product.category.pk }}" class="grey-text">
      <h5>{{ product.category }}</h5>
    </a>
    <h5>
      <strong>
        <a href="{% url 'shop:product_detail' product.slug %}" class="dark-grey-text">
          {{ product }}
          {% if product.label_text %}
            <span class="badge badge-pill {{ product.get_label_colour_display }}-color">
              {{ product.label_text }}
            </span>
          {% endif %}
        </a>
      </strong>
    </h5>

    {% if product.get_avg_rating %}
      <p class="text-muted">
        {{ product.get_avg_rating|rating_to_stars }}
      </p>
    {% endif %}

    <h4 class="font-weight-bold blue-text">
      <strong>${{ product.get_final_price }}</strong>
    </h4>

  </div>
  <!--Card content-->

</div>
<!--Card-->

shop/templates/shop/product_detail.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% load my_extras %}

{% block title %}{{ product }}{% endblock title %}

{% block content %}
  <!--Main layout-->
  <main>
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img id="product-image" src="{% if product.images.first %}{{ product.images.first.image.url }}{% else %}{% static 'shop/img/no_image.png' %}{% endif %}" class="img-fluid" alt="">

          {% if product.images.all|length > 1 %}
            <nav class="mt-3">
              <ul class="pagination pg-blue m-0 js-image-pagination">
                {% for img in product.images.all %}
                  <li class="page-item {% if forloop.first %}active{% endif %}" data-src="{{ img.image.url }}">
                    <a class="page-link" href="#">{{ forloop.counter }}</a>
                  </li>
                {% endfor %}
              </ul>
            </nav>
          {% endif %}

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          {% if not product.available %}
            <div class="alert alert-danger">Out of Stock</div>
          {% endif %}

          <!--Content-->
          <div class="p-4">

            <div>
              <a href="{% url 'shop:product_list' %}?category={{ product.category.pk }}" class="text-muted">
                <h5>{{ product.category }}<h5>
              </a>
            </div>

            <h1 class="font-weight-bold mb-3">
              {{ product }}
              {% if product.label_text %}
                <span class="badge {{ product.get_label_colour_display }}-color mr-1">
                  {{ product.label_text }}
                </span> 
              {% endif %}
            </h1>

            {% if product.get_num_rating %}
              <p>
                <span class="text-muted mr-2">
                  {{ product.get_avg_rating|rating_to_stars }}
                </span>
                {{ product.get_avg_rating }} out of 5 ({{ product.get_num_rating }} ratings)
              </p>
            {% endif %}

            <h2>
              {% if product.discount_price %}
                <span class="mr-1">
                  <del>${{ product.price }}</del>
                </span>
              {% endif %}
              <span>${{ product.get_final_price }}</span>
            </h2>

            {% if product.available %}
              <form action="{% url 'shop:add_to_cart' product.pk %}" method="POST" class="d-flex justify-content-left mt-5">
                <!-- Default input -->
                {# <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px"> #}
                {% csrf_token %}
                {{ a_form.quantity }}
                <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                  <i class="fas fa-shopping-cart ml-1"></i>
                </button>

              </form>
            {% endif %}

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6">

          <h4 class="my-4 h4 text-center">Description</h4>

          <p>{{ product.description|markdown }}</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6">

          <h4 class="my-4 h4 text-center">Reviews</h4>

          {% for review in reviews %}
            <div class="card mb-4">
              <div class="card-body">
                <p class="text-muted">{{ review.rating|rating_to_stars }}</p>
                {{ review.comment|linebreaks }}
                <small class="text-muted">
                  {{ review.user.get_full_name }} on {{ review.created }}
                </small>
              </div>
            </div>
          {% endfor %}

          {% if reviews %}
            {% include 'pagination.html' with page=reviews %}
          {% endif %}

          <h5>Add a review</h5>
          <form action="{% url 'shop:review_create' product.pk %}" method="POST">
            {% csrf_token %}
            <p class="mb-2 text-muted" style="font-size:22px;">
              <i class="fas fa-star js-star cursor-pointer" data-value=1></i>
              <i class="fas fa-star js-star cursor-pointer" data-value=2></i>
              <i class="fas fa-star js-star cursor-pointer" data-value=3></i>
              <i class="fas fa-star js-star cursor-pointer" data-value=4></i>
              <i class="fas fa-star js-star cursor-pointer" data-value=5></i>
            </p>
            {{ r_form|crispy }}
            <button class="btn btn-md btn-primary">Submit</button>
          </form>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      {% if recommended_products %}
        <hr>

        <!--Section: Products v.3-->
        <section class="text-center mb-4">

          <h4 class="my-4 h4">People who bought this also bought</h4>

          <!--Grid row-->
          <div class="row wow fadeIn">

            {% for product in recommended_products %}
              <!--Grid column-->
              <div class="col-lg-3 col-md-6 mb-4">
                {% include 'shop/product_card.html' %}
              </div>
              <!--Grid column-->
            {% endfor %}

          </div>
          <!--Grid row-->

        </section>
        <!--Section: Products v.3-->
      {% endif %}

    </div>
  </main>
  <!--Main layout-->
{% endblock content %}

{% block extra_scripts %}
  <script type="text/javascript" src="{% static 'mystatic/js/image_pagination.js' %}"></script>
  <script type="text/javascript" src="{% static 'shop/js/rating.js' %}"></script>
{% endblock extra_scripts %}